# Generated by Django 4.2.6 on 2023-10-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_measurement_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
